### ISSUE TITLE
create-installer-windows script error

### ISSUE THREAD

**Issue by Jeff-Cortese** [stokingerl/Angular2-Electron-Boilerplate#1]
Hi, great repo!
  I am getting some errors when trying to build a windows installer via `npm run full-build-windows`. It appears to fail on the `create-installer-windows` script due to a missing `createinstaller.js` file. Any ideas how to fix this?

npm log
````bash
...

> electron-angular-boilerplate@0.0.0 create-installer-windows C:\Users\jcortese\source\Angular2-Electron-Boilerplate-master\Angular2-Electron-Boilerplate-master
> node installers/windows/createinstaller.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\jcortese\source\Angular2-Electron-Boilerplate-master\Angular2-Electron-Boilerplate-master\installers\windows\createinstaller.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

...
````

**Comment by stokingerl** [comment]
Hmm, I'll have to take a look at this tonight. I haven't been able to try to run this script on a windows machine yet so I'll give it a go when I get home from work.

I was running into a similar issue on Mac OS, I ended up needing wine installed.

Have you been able to run the other build scripts for windows? Like `npm run package-windows`?

**Comment by Jeff-Cortese** [comment]
Yeah, package-windows appeared to work fine. I don't plan on needing to build an exe anytime soon, so this isn't urgent or anything.

**Comment by stokingerl** [comment]
So I've taken a deeper dive into this and I actually can't seem to get this script running at all anymore.

I'm taking a look into [Electron Builder](https://www.npmjs.com/package/electron-builder) for packaging and installing. Hopefully I can move everything over in the next couple of days.

**Comment by linux-nerd** [comment]
Is there any update on this?

**Comment by iamcharnjeet** [comment]
any update on this I am still facing this issue and I need the .exe file. Can you provide me detail how I can fixed this or get .exe file.
